call coc#config('languageserver', {
  \ 'haskell': {
  \   "command": "haskell-language-server-wrapper",
  \   "args": ["--lsp"],
  \   "trace.server": "verbose",
  \   "rootPatterns": ["*.cabal", "cabal.project", "hie.yaml"],
  \   "filetypes": ["haskell"],
  \   "initializationOptions": {},
  \   "settings": {
  \     "haskell": {
  \       "formattingProvider": "fourmolu",
  \       "plugin": {
  \         "stan": { "globalOn": v:false }
  \       }
  \     }
  \   }
  \ }
  \})
